name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AGENCY_COUNT=6
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - FIRST_NAME=Julian1
      - LAST_NAME=Garcia1
      - DOCUMENT=123456781
      - BIRTHDATE=2000-01-01
      - NUMBER=75741
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data:/data

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - FIRST_NAME=Julian2
      - LAST_NAME=Garcia2
      - DOCUMENT=123456782
      - BIRTHDATE=2000-01-01
      - NUMBER=75742
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data:/data

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - FIRST_NAME=Julian3
      - LAST_NAME=Garcia3
      - DOCUMENT=123456783
      - BIRTHDATE=2000-01-01
      - NUMBER=75743
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data:/data

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - FIRST_NAME=Julian4
      - LAST_NAME=Garcia4
      - DOCUMENT=123456784
      - BIRTHDATE=2000-01-01
      - NUMBER=75744
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data:/data

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - FIRST_NAME=Julian5
      - LAST_NAME=Garcia5
      - DOCUMENT=123456785
      - BIRTHDATE=2000-01-01
      - NUMBER=75745
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data:/data

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
